# Default Theme
if patched_font_in_use; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'0'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'255'}

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}


# Format: segment_name background_color foreground_color [non_default_separator]

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"tmux_session_info 3 0 "  \
		"hostname 20 0" \
		"ifstat 30 255" \
                #"ifstat_sys 24 255" \
	        "lan_ip 33 255" \
		"wan_ip 15 0" \  # ${TMUX_POWERLINE_SEPARATOR_LEFT_THIM} " \
		#"vcs_branch 2 255" \
		#"vcs_compare 60 255 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}" \
		#"vcs_staged 64 255 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}" \
		#"vcs_modified 9 255" \
		#"vcs_others 245 0 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}" \
	)
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		#"earthquake 3 0" \
		#"pwd 89 211" \
	        #"mailcount 9 255" \
		#"now_playing 234 37" \
		"weather 4 255" \ 
                #"cpu 240 136 ${TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD} ${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR}" \
		#"load 237 167" \
                #"tmux_mem_cpu_load 0 10 ${TMUX_POWERLINE_SEPARATOR_LEFT_BOLD} " \
		#"xkb_layout 1 0" \
		#"date_day 0 255" \
		#"date 0 255 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"time 0 255 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"utc_time 235 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \	
		"battery 7 0" \
                #"rainbarf 0 ${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR}" \
                "xkb_layout 8 0" \

	)
fi
